### ISSUE TITLE
Google and Yahoo auth not working with https callback url

### ISSUE THREAD

**Issue by sussegaduss** [jaliss/securesocial#13]
When i try to make an authentication with google or yahoo providers using as callbackurl https://www.mydomain.com/auth/google i get the following error:

@68ncimf3o
Error authenticating user

No route found
No route able to invoke action https://www.mydomain.com/auth/google with arguments {} was found.

play.exceptions.NoRouteFoundException: No route found
    at play.mvc.Router.reverse(Router.java:534)
    at play.mvc.Router.reverse(Router.java:313)
    at play.libs.OpenID.verify(OpenID.java:138)
    at securesocial.provider.OpenIDProvider.doAuth(OpenIDProvider.java:97)
    at securesocial.provider.OpenIDOAuthHybridProvider.doAuth(OpenIDOAuthHybridProvider.java:85)
    at securesocial.provider.IdentityProvider.authenticate(IdentityProvider.java:67)
    at controllers.securesocial.SecureSocial.authenticate(SecureSocial.java:189)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:546)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:500)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:476)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:471)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:159)
    at Invocation.HTTP Request(Play!)

I found out that OpenIdProvider class from secureSocial module, on method getFullUrl() is using  OpenID.java.
On line 138 of OpenID.java i discovered that the 'else' part of this code:

```
        if (returnAction != null && returnAction.startsWith("http://")) {
            url += "&openid.return_to=" + URLEncoder.encode(returnAction, "utf8");
        } else {
           url += "&openid.return_to=" + URLEncoder.encode(Request.current().getBase() + Router.reverse(returnAction), "utf8");
        }
```

is causing the error.. it seems like Router.reverse is causing this error.

im using play 1.2.3

is it possible to use the module with https when i use hibrid providers? can anyone help me with it?

**Comment by dumedeiros** [comment]
Hi Jaliss, Hi venkatrohith...

I'm with the same problem here.
I'm getting the same error as venkatrohith.

-> ERROR ~ Request token is missing in OpenID+OAuth callback.  Provider: yahoo
-> securesocial.provider.AuthenticationException
-> ERROR ~ Error authenticating user
-> securesocial.provider.AuthenticationException

All my attempts to use OpenId failed, using GoogleOpenIDProvider and GoogleProvider as well.

**Comment by jaliss** [comment]
What version are you using? Google works for me in the latest milestone.

**Comment by dumedeiros** [comment]
Hi Jaliss.

I'm using the "securesocial-0.2.6" version in Play 1.4.0

In debug mode I can see that, inside OpenIDOAuthHybridProvider the 

<b>Scope.Params params = Scope.Params.current();</b>

contains the user data, but the 

<b>OPENID_OAUTH_REQUEST_TOKEN </b> is missing. 
<b> [String token = params.get(OPENID_OAUTH_REQUEST_TOKEN);</b>

I'm almost implementing a YahooOAuth2Provider based on any of your OAuth2Provider.
Is there any advantage on using OpenId over Oauth2?

Thanks! =D

**Comment by jaliss** [comment]
Go ahead and implement a oauth2 based one then.  When I wrote that version Yahoo only had the hybrid protocol. It is possible that Yahoo that not support that anymore and pure oauth2 is needed.
