### ISSUE TITLE
Login redirect login from facebook

### ISSUE THREAD

**Issue by ElielBarone** [jaliss/securesocial#178]
Hi, I again, so in my attempt to login with facebook, I came across with a new problem... when I click to loggin:

[debug] application - [securesocial] authorizationUrl = https://graph.facebook.com/oauth/authorize
[debug] application - [securesocial] redirecting to: [https://graph.facebook.com/oauth/authorize?scope=email&client_id={... myKey}&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauthenticate%2Ffacebook&response_type=code&state=0af4d137-bdad-466c-aac0-59ad3cecc224]

I navigate to facebook and I will be able to make a login, but when I execute, the facebook will redirect to:
http://localhost:9000/authenticate/facebook?state=69ae42fa-58b7-4d87-8ac3-6074c79c5baf&code=AQB0uIra9e2QNV13a7_-ih3MIysIJalY6pn4mRZFxc5AUU08kcRe7ghvrNvGTyVVUO4WyR5o_8hi7Q1xyt0Q1ZiiF25POiUZv6LzqxLWDCwsQkPJDU_Ty0QIamJeHx6N-BTRuuoxiuqsGgzZurECDWABd__9QV1EOh7YJlcfxLGHRNI3Jxk1jH2BX60H--P39Dxl5wROUzWZN2ctr8pbBUud#_=_

and an message will appear:
An error occurred while logging you in. Please try again.

on the console:

[error] application - [securesocial] timed out trying to get an access token for provider facebook
[error] application - Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null
        at securesocial.core.OAuth2Provider$$anonfun$securesocial$core$OAuth2Provider$$getAccessToken$1.apply(OAuth2Provider.scala:63) ~[securesocial_2.9.1-master.jar:master]
        at securesocial.core.OAuth2Provider$$anonfun$securesocial$core$OAuth2Provider$$getAccessToken$1.apply(OAuth2Provider.scala:60) ~[securesocial_2.9.1-master.jar:master]
        at play.api.libs.concurrent.NotWaiting$class.fold(Promise.scala:29) ~[play_2.9.1.jar:2.0.4]
        at play.api.libs.concurrent.Thrown.fold(Promise.scala:35) ~[play_2.9.1.jar:2.0.4]
        at securesocial.core.OAuth2Provider.securesocial$core$OAuth2Provider$$getAccessToken(OAuth2Provider.scala:60) ~[securesocial_2.9.1-master.jar:master]
        at securesocial.core.OAuth2Provider$$anonfun$2$$anonfun$apply$6$$anonfun$apply$9.apply(OAuth2Provider.scala:103) ~[securesocial_2.9.1-master.jar:master]

**Comment by harryarsh** [comment]
@ElielBarone Hey Eliel I'm facing the exact same issue, can you please tell me how did you solve it?

**Comment by ElielBarone** [comment]
Hi @harryarsh, I solve as @jaliss said, adding an alias in my etc, so you need  redirect to this alias.

how to do
open the file c:\windows\system32\drivers\etc\hosts

add the line
127.0.0.1       mindbind

test your app with this url
http://mindbind:3000/

add this url to facebook
http://mindbind:3000/

you can solve running your app on heroturko for example, so you will have a domain
