### ISSUE TITLE
New Google provider integration not working

### ISSUE THREAD

**Issue by mickgiles** [jaliss/securesocial#453]
Maybe it's just me but I believe I have made all the needed adjustments yet still get these errors from various google accounts...

[error] s.c.p.GoogleProvider - [securesocial] error retrieving profile information from Google
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.2.jar:2.3.2]
    at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.2.jar:2.3.2]
    at play.api.libs.json.JsResult$class.fold(JsResult.scala:77) ~[play-json_2.11-2.3.2.jar:2.3.2]
    at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[play-json_2.11-2.3.2.jar:2.3.2]
    at play.api.libs.json.JsValue$class.as(JsValue.scala:65) ~[play-json_2.11-2.3.2.jar:2.3.2]
[error] s.c.p.GoogleProvider - [securesocial] error authenticating user
securesocial.core.AuthenticationException: null
    at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:78) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
    at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:74) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.1.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) ~[scala-library-2.11.1.jar:na]
    at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.1.jar:na]
[error] s.c.ProviderController - Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null
    at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:78) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
    at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:74) ~[securesocial_2.11-master-SNAPSHOT.jar:master-SNAPSHOT]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [scala-library-2.11.1.jar:na]
    at scala.util.Try$.apply(Try.scala:191) [scala-library-2.11.1.jar:na]

**Comment by PhilAndrew** [comment]
I discovered this problem, I wish that the error message in the logs pointed to this issue or told me what to do as it took me ages to locate this issue ticket.
