### ISSUE TITLE
AuthenticationException triggered by bot traffic to /auth/authenticate

### ISSUE THREAD

**Issue by anfuerer** [jaliss/securesocial#523]
We see repeated traffic from a Google IP (looks like it's the google bot) to /auth/authenticate using invalid  or outdated session ids. Securesocial responds with a `500 Internal Server Error` and always logs an exception in the log:

```
[error] s.c.p.GoogleProvider - [securesocial] missing sid in session.
[error] application - 

! @6l6l2defd - Internal server error, for (GET) [/auth/authenticate/google?state=123&code=456] ->

play.api.Application$$anon$1: Execution exception[[AuthenticationException: null]]
	at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.7.jar:2.3.7]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.7.jar:2.3.7]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.7.jar:2.3.7]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: securesocial.core.AuthenticationException: null
	at securesocial.core.OAuth2Provider$$anonfun$authenticate$1$$anonfun$7.apply(OAuth2Provider.scala:124) ~[classes/:na]
	at securesocial.core.OAuth2Provider$$anonfun$authenticate$1$$anonfun$7.apply(OAuth2Provider.scala:122) ~[classes/:na]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.11.1.jar:na]
	at securesocial.core.OAuth2Provider$$anonfun$authenticate$1.apply(OAuth2Provider.scala:121) ~[classes/:na]
	at securesocial.core.OAuth2Provider$$anonfun$authenticate$1.apply(OAuth2Provider.scala:110) ~[classes/:na]
```

In my opinion this should not trigger a 500, but should be rejected as an invalid request (without exception logging). I would expect sth like a `401 Unauthorized` or a `400 Bad Request`

**Comment by jaliss** [comment]
this should be fixed by #550
