### ISSUE TITLE
Failing to Authenticate with Google

### ISSUE THREAD

**Issue by Christewart** [jaliss/securesocial#527]
I am trying to have a user log in with Google, but I am getting an error on the call back. Here is the stack trace:

[error] s.c.p.GoogleProvider - [securesocial] error retrieving profile information from Google
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(error.expected.jsstring,WrappedArray())))))
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.7.jar:2.3.7]
	at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67) ~[play-json_2.11-2.3.7.jar:2.3.7]
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:77) ~[play-json_2.11-2.3.7.jar:2.3.7]
	at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[play-json_2.11-2.3.7.jar:2.3.7]
	at play.api.libs.json.JsValue$class.as(JsValue.scala:65) ~[play-json_2.11-2.3.7.jar:2.3.7]
[error] s.c.p.GoogleProvider - [securesocial] error authenticating user
securesocial.core.AuthenticationException: null
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:73) ~[securesocial_2.11-3.0-M3.jar:3.0-M3]
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:69) ~[securesocial_2.11-3.0-M3.jar:3.0-M3]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [suredbits-core-assembly-2.3.1.jar:2.3.1]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [suredbits-core-assembly-2.3.1.jar:2.3.1]
	at scala.util.Try$.apply(Try.scala:191) [suredbits-core-assembly-2.3.1.jar:2.3.1]
[error] s.c.ProviderController - Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:73) ~[securesocial_2.11-3.0-M3.jar:3.0-M3]
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:69) ~[securesocial_2.11-3.0-M3.jar:3.0-M3]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [suredbits-core-assembly-2.3.1.jar:2.3.1]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) [suredbits-core-assembly-2.3.1.jar:2.3.1]
	at scala.util.Try$.apply(Try.scala:191) [suredbits-core-assembly-2.3.1.jar:2.3.1]

**Comment by Christewart** [comment]
The solution was to enable the 'Google+ Api' in the API section of the Google Developer Console.
