### ISSUE TITLE
play.api.libs.json.JsDefined cannot be cast to play.api.libs.json.JsArray

### ISSUE THREAD

**Issue by meloniasty** [jaliss/securesocial#570]
I'm using:
play 2.4.3
secure social master-SNAPSHOT build today
scala 2.10.6
and using Google provider

```
[error] s.c.p.GoogleProvider - [securesocial] error retrieving profile information from Google
java.lang.ClassCastException: play.api.libs.json.JsDefined cannot be cast to play.api.libs.json.JsArray
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$2.apply(GoogleProvider.scala:67) ~[securesocial_2.10.jar:master-SNAPSHOT]
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$2.apply(GoogleProvider.scala:54) ~[securesocial_2.10.jar:master-SNAPSHOT]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206) ~[scala-library-2.10.6.jar:na]
	at scala.util.Try$.apply(Try.scala:161) ~[scala-library-2.10.6.jar:na]
	at scala.util.Success.map(Try.scala:206) ~[scala-library-2.10.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.10.6.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.10.6.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [scala-library-2.10.6.jar:na]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [na:1.8.0_66]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [na:1.8.0_66]
[error] s.c.ProviderController - Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:75) ~[securesocial_2.10.jar:master-SNAPSHOT]
	at securesocial.core.providers.GoogleProvider$$anonfun$fillProfile$1.applyOrElse(GoogleProvider.scala:71) ~[securesocial_2.10.jar:master-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library-2.10.6.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library-2.10.6.jar:na]
```

**Comment by jaliss** [comment]
@meloniasty this was fixed in #571. Try the latest snapshot and let me know if you have issues.
