### ISSUE TITLE
Error using Google: Unable to log user in. An exception was thrown

### ISSUE THREAD

**Issue by sadiqkhoja** [jaliss/securesocial#586]
Version: "ws.securesocial" %% "securesocial" % "3.0-M3"
Play Version: 2.3.7

Steps to reproduce:
1) User tries to use google authentication to login to my application
2) WithProvider implementing securesocial.core.java.Authorization rejects user authorization
3) User logs out of google and tries another google account that has authorization to access my application

Following error is thrown:
`2016-03-25 00:18:40,355 ERROR [play-akka.actor.default-dispatcher-241] s.c.ProviderController [Logger.scala:141] Unable to log user in. An exception was thrown
java.lang.NullPointerException: null
    at securesocial.core.java.BaseUserService.link(BaseUserService.java:95) ~[ws.securesocial.securesocial_2.11-3.0-M3.jar:3.0-M3]
    at securesocial.controllers.BaseProviderController$$anonfun$handleAuth$1$$anonfun$apply$3$$anonfun$apply$4.apply(ProviderController.scala:126) ~[ws.securesocial.securesocial_2.11-3.0-M3.jar:3.0-M3]
    at securesocial.controllers.BaseProviderController$$anonfun$handleAuth$1$$anonfun$apply$3$$anonfun$apply$4.apply(ProviderController.scala:94) ~[ws.securesocial.securesocial_2.11-3.0-M3.jar:3.0-M3]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249) ~[org.scala-lang.scala-library-2.11.1.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.1.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [org.scala-lang.scala-library-2.11.1.jar:na]
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [com.typesafe.akka.akka-actor_2.11-2.3.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.1.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.11.1.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.1.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.1.jar:na]`

**Comment by pedalpete** [comment]
Did you ever figure this out? I'm seeing many users able to login, but random users unable. Seems to effect Facebok more than google logins.

**Comment by jaliss** [comment]
I can't reproduce this. Please re-open if needed.
